use anyhow::{Context, Result};
use std::fs;
use std::path::Path;

use crate::model::{Project, Skill};
use crate::util;

pub mod claude;
pub mod cursor;
pub mod opencode;

pub trait Provider {
    fn name(&self) -> &str;
    fn generate(&self, project: &Project, ai_dir: &Path) -> Result<()>;
    fn cleanup(&self) -> Result<usize> {
        Ok(0)
    }
}

pub fn all() -> Vec<Box<dyn Provider>> {
    vec![
        Box::new(claude::Claude),
        Box::new(cursor::Cursor),
        Box::new(opencode::OpenCode),
    ]
}

pub fn known_names() -> Vec<String> {
    all().into_iter().map(|p| p.name().to_string()).collect()
}

pub fn resolve(names: &[String]) -> Result<Vec<Box<dyn Provider>>> {
    let known = known_names();
    for name in names {
        if !known.contains(name) {
            anyhow::bail!(
                "unknown provider '{}'. Known providers: {}",
                name,
                known.join(", ")
            );
        }
    }
    Ok(all()
        .into_iter()
        .filter(|p| names.contains(&p.name().to_string()))
        .collect())
}

pub const GENERATED: &str =
    "<!-- Generated by dotai from .ai/. Do not edit. Run `dotai gen` to regenerate. -->\n";

pub fn frontmatter(entries: &[(&str, String)]) -> String {
    let mut s = String::from("---\n");
    for (k, v) in entries {
        if v.starts_with('\n') {
            s.push_str(&format!("{}:{}\n", k, v));
        } else {
            s.push_str(&format!("{}: {}\n", k, v));
        }
    }
    s.push_str("---\n");
    s
}

pub fn comma_list(items: &[String]) -> String {
    items.join(", ")
}

pub fn yaml_list(items: &[String]) -> String {
    let mut s = String::from("\n");
    for item in items {
        s.push_str(&format!("  - \"{}\"\n", item.replace('"', "\\\"")));
    }
    s
}

pub fn dedupe(items: Vec<String>) -> Vec<String> {
    let mut out = Vec::new();
    for item in items {
        if !out.contains(&item) {
            out.push(item);
        }
    }
    out
}

pub fn write_md_with_fm(path: &Path, meta: &[(&str, String)], body: &str) -> Result<()> {
    let mut content = frontmatter(meta);
    content.push_str(GENERATED);
    content.push_str(body);
    content.push('\n');
    util::write(path, &content)
}

pub fn write_skill(base: &Path, skill: &Skill, meta: &[(&str, String)]) -> Result<()> {
    let dst = base.join(&skill.name);
    fs::create_dir_all(&dst).with_context(|| format!("Failed to create {}", dst.display()))?;
    if let Some(src) = &skill.src_dir {
        for entry in
            fs::read_dir(src).with_context(|| format!("Failed to read {}", src.display()))?
        {
            let entry = entry?;
            let name = entry.file_name();
            if name == "SKILL.md" {
                continue;
            }
            if entry.file_type()?.is_dir() {
                util::copy_dir(&entry.path(), &dst.join(&name), false)?;
            } else {
                fs::copy(entry.path(), dst.join(&name))
                    .with_context(|| format!("Failed to copy {}", entry.path().display()))?;
            }
        }
    }
    let mut content = frontmatter(meta);
    content.push_str(GENERATED);
    content.push_str(&skill.body);
    content.push('\n');
    util::write(&dst.join("SKILL.md"), &content)?;
    remove_extra_resources(skill.src_dir.as_deref(), &dst)
}

fn remove_extra_resources(src: Option<&Path>, dst: &Path) -> Result<()> {
    let entries = fs::read_dir(dst).with_context(|| format!("Failed to read {}", dst.display()))?;
    for entry in entries {
        let entry = entry?;
        let name = entry.file_name();
        if name == "SKILL.md" {
            continue;
        }
        let src_path = src.map(|s| s.join(&name));
        if entry.file_type()?.is_dir() {
            if src_path.as_deref().map(|p| p.is_dir()).unwrap_or(false) {
                remove_extra_resources(src_path.as_deref(), &entry.path())?;
                remove_empty(&entry.path());
            } else {
                fs::remove_dir_all(entry.path())
                    .with_context(|| format!("Failed to remove {}", entry.path().display()))?;
            }
        } else if entry.file_type()?.is_file()
            && !src_path.as_deref().map(|p| p.is_file()).unwrap_or(false)
        {
            fs::remove_file(entry.path())
                .with_context(|| format!("Failed to remove {}", entry.path().display()))?;
        }
    }
    Ok(())
}

pub fn is_generated(content: &str) -> bool {
    content.contains(GENERATED)
}

pub fn remove_empty(dir: &Path) {
    if let Ok(mut entries) = fs::read_dir(dir) {
        if entries.next().is_none() {
            let _ = fs::remove_dir(dir);
        }
    }
}

/// Remove generated files in `dir` (extension `ext`) whose stem is not in `keep`.
pub fn remove_stale_files(dir: &Path, ext: &str, keep: &[String]) -> Result<usize> {
    if !dir.exists() {
        return Ok(0);
    }
    let mut removed = 0;
    let entries = fs::read_dir(dir).with_context(|| format!("Failed to read {}", dir.display()))?;
    for entry in entries {
        let entry = entry?;
        let name = entry.file_name().to_string_lossy().to_string();
        if name.starts_with('.') || !name.ends_with(ext) {
            continue;
        }
        if !entry.file_type().map(|t| t.is_file()).unwrap_or(false) {
            continue;
        }
        let stem = Path::new(&name)
            .file_stem()
            .unwrap_or_default()
            .to_string_lossy()
            .to_string();
        if keep.contains(&stem) {
            continue;
        }
        let path = entry.path();
        let content = fs::read_to_string(&path).unwrap_or_default();
        if is_generated(&content) {
            fs::remove_file(&path)
                .with_context(|| format!("Failed to remove {}", path.display()))?;
            removed += 1;
        }
    }
    remove_empty(dir);
    Ok(removed)
}

/// Remove generated skill directories (dirs with a generated SKILL.md) not in `keep`.
pub fn remove_stale_skills(base: &Path, keep: &[String]) -> Result<usize> {
    if !base.exists() {
        return Ok(0);
    }
    let mut removed = 0;
    let entries =
        fs::read_dir(base).with_context(|| format!("Failed to read {}", base.display()))?;
    for entry in entries {
        let entry = entry?;
        let name = entry.file_name().to_string_lossy().to_string();
        if name.starts_with('.') {
            continue;
        }
        if !entry.file_type().map(|t| t.is_dir()).unwrap_or(false) {
            continue;
        }
        let skill_md = entry.path().join("SKILL.md");
        if !skill_md.exists() {
            continue;
        }
        let content = fs::read_to_string(&skill_md).unwrap_or_default();
        if !is_generated(&content) || keep.contains(&name) {
            continue;
        }
        fs::remove_dir_all(entry.path())
            .with_context(|| format!("Failed to remove {}", entry.path().display()))?;
        removed += 1;
    }
    remove_empty(base);
    Ok(removed)
}

pub fn summary(
    name: &str,
    rules: usize,
    agents: usize,
    skills: usize,
    commands: usize,
    removed: usize,
) {
    let mut parts = Vec::new();
    if rules > 0 {
        parts.push(format!(
            "{} rule{}",
            rules,
            if rules == 1 { "" } else { "s" }
        ));
    }
    if agents > 0 {
        parts.push(format!(
            "{} agent{}",
            agents,
            if agents == 1 { "" } else { "s" }
        ));
    }
    if skills > 0 {
        parts.push(format!(
            "{} skill{}",
            skills,
            if skills == 1 { "" } else { "s" }
        ));
    }
    if commands > 0 {
        parts.push(format!(
            "{} command{}",
            commands,
            if commands == 1 { "" } else { "s" }
        ));
    }
    let mut msg = format!(
        "  Wrote {} ({})",
        name,
        if parts.is_empty() {
            "no items".to_string()
        } else {
            parts.join(", ")
        }
    );
    if removed > 0 {
        msg.push_str(&format!(
            "; removed {} stale file{}",
            removed,
            if removed == 1 { "" } else { "s" }
        ));
    }
    println!("{}", msg);
}
