use anyhow::{Context, Result};
use std::fs;
use std::io::Write;
use std::path::Path;

use crate::providers;

pub fn run() -> Result<()> {
    println!("This will remove AGENTS.md and every file generated by dotai in:");
    println!("  - .claude/");
    println!("  - .cursor/");
    println!("  - .opencode/");
    println!("The .ai/ directory and files you created manually (without the dotai");
    println!("generated marker) are kept.");
    print!("Are you sure you want to remove these files? [y/N] ");
    std::io::stdout().flush()?;

    let mut input = String::new();
    std::io::stdin().read_line(&mut input)?;
    let answer = input.trim().to_ascii_lowercase();
    if answer != "y" && answer != "yes" {
        println!("Aborted.");
        return Ok(());
    }

    let mut removed = 0;
    if Path::new("AGENTS.md").exists() {
        fs::remove_file("AGENTS.md").with_context(|| "Failed to remove AGENTS.md")?;
        println!("Removed AGENTS.md");
        removed += 1;
    }
    for provider in providers::all() {
        removed += provider.cleanup()?;
    }
    println!("Removed {} generated file(s).", removed);
    Ok(())
}
