use clap::{Args, Parser, Subcommand, ValueEnum};

mod ai_dir;
mod commands;
mod config;
mod frontmatter;
mod model;
mod providers;
mod state;
mod template;
mod translate;
mod util;

#[derive(Parser)]
#[command(
    name = "dotai",
    version,
    about = "Single source of truth for AI configs"
)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    #[command(about = "Create .ai directory from template (or add agents/skills/commands/rules)")]
    New(NewArgs),
    #[command(about = "Generate provider configs from .ai directory")]
    Gen(GenArgs),
    #[command(about = "List available providers")]
    Providers,
    #[command(about = "Remove AGENTS.md and all files generated by dotai")]
    Clear,
}

#[derive(Args)]
struct NewArgs {
    #[command(subcommand)]
    kind: Option<NewKind>,
}

#[derive(Clone, Copy, ValueEnum)]
enum ModelLevel {
    Small,
    Medium,
    Large,
}

impl ModelLevel {
    fn as_str(self) -> &'static str {
        match self {
            ModelLevel::Small => "small",
            ModelLevel::Medium => "medium",
            ModelLevel::Large => "large",
        }
    }
}

#[derive(Clone, Copy, ValueEnum)]
enum EffortLevel {
    Low,
    Medium,
    High,
    Xhigh,
    Max,
}

impl EffortLevel {
    fn as_str(self) -> &'static str {
        match self {
            EffortLevel::Low => "low",
            EffortLevel::Medium => "medium",
            EffortLevel::High => "high",
            EffortLevel::Xhigh => "xhigh",
            EffortLevel::Max => "max",
        }
    }
}

#[derive(Subcommand)]
enum NewKind {
    #[command(about = "Create a new agent in .ai/agents/")]
    Agent {
        #[arg(value_name = "NAME")]
        name: String,
        #[arg(
            long,
            value_enum,
            default_value_t = ModelLevel::Medium,
            help = "Model size: small, medium or large (mapped per provider in dotai.json)"
        )]
        model: ModelLevel,
        #[arg(
            long,
            value_enum,
            default_value_t = EffortLevel::Medium,
            help = "Reasoning effort: low, medium, high, xhigh or max"
        )]
        effort: EffortLevel,
    },
    #[command(about = "Create a new skill in .ai/skills/")]
    Skill {
        #[arg(value_name = "NAME")]
        name: String,
    },
    #[command(about = "Create a new command in .ai/commands/")]
    Command {
        #[arg(value_name = "NAME")]
        name: String,
    },
    #[command(about = "Create a new rule in .ai/rules/")]
    Rule {
        #[arg(value_name = "NAME")]
        name: String,
    },
    #[command(about = "Create .ai/AI.md if missing")]
    Ai,
}

#[derive(Args)]
struct GenArgs {
    #[arg(
        value_name = "PROVIDER",
        help = "Providers to generate (default: from ~/.config/dotai/dotai.json)"
    )]
    providers: Vec<String>,
    #[arg(long, help = "Overwrite files that existed before dotai managed them")]
    force: bool,
}

fn main() -> anyhow::Result<()> {
    let cli = Cli::parse();
    match cli.command {
        Commands::New(args) => {
            let kind = args.kind.map(|k| match k {
                NewKind::Agent {
                    name,
                    model,
                    effort,
                } => commands::new_cmd::NewKind::Agent(
                    name,
                    model.as_str().to_string(),
                    effort.as_str().to_string(),
                ),
                NewKind::Skill { name } => commands::new_cmd::NewKind::Skill(name),
                NewKind::Command { name } => commands::new_cmd::NewKind::Command(name),
                NewKind::Rule { name } => commands::new_cmd::NewKind::Rule(name),
                NewKind::Ai => commands::new_cmd::NewKind::Ai,
            });
            commands::new_cmd::run(kind)?;
        }
        Commands::Gen(args) => commands::gen_cmd::run(args.providers, args.force)?,
        Commands::Clear => commands::clear_cmd::run()?,
        Commands::Providers => {
            println!(
                "Available providers: {}",
                providers::known_names().join(", ")
            );
            match config::load()? {
                Some(cfg) => println!(
                    "Configured in {}: {}",
                    config::path().display(),
                    cfg.providers.join(", ")
                ),
                None => println!(
                    "No config at {}; pass providers to `dotai gen` (e.g. `dotai gen claude opencode cursor`)",
                    config::path().display()
                ),
            }
        }
    }
    Ok(())
}
