use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use crate::util;

pub const LEGACY_MARKER: &str =
    "<!-- Generated by dotai from .ai/. Do not edit. Run `dotai gen` to regenerate. -->";

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Outcome {
    Written,
    Adopted,
    Unchanged,
    SkippedPreExisting,
}

#[derive(Debug, Default, Serialize, Deserialize)]
pub struct Manifest {
    #[serde(default)]
    files: BTreeMap<String, String>,
}

impl Manifest {
    pub fn load(ai_dir: &Path) -> Result<Self> {
        let path = ai_dir.join("manifest.json");
        if !path.exists() {
            return Ok(Self::default());
        }
        let content = fs::read_to_string(&path)
            .with_context(|| format!("Failed to read {}", path.display()))?;
        let manifest: Manifest = serde_json::from_str(&content)
            .with_context(|| format!("Invalid manifest {}", path.display()))?;
        Ok(manifest)
    }

    pub fn save(&self, ai_dir: &Path) -> Result<()> {
        util::write(
            &ai_dir.join("manifest.json"),
            &serde_json::to_string_pretty(self)?,
        )
    }

    pub fn owns(&self, rel: &str) -> bool {
        self.files.contains_key(rel)
    }

    pub fn owns_any(&self, prefix: &str) -> bool {
        let prefix = format!("{}/", prefix);
        self.files.keys().any(|k| k.starts_with(&prefix))
    }

    /// Write `content` to `rel` (relative to the project root) unless nothing
    /// changed since the last run. Returns how the file was handled.
    pub fn write_if_changed(&mut self, rel: &str, content: &str, force: bool) -> Result<Outcome> {
        self.write_if_changed_bytes(rel, content.as_bytes(), force)
    }

    pub fn write_if_changed_bytes(
        &mut self,
        rel: &str,
        data: &[u8],
        force: bool,
    ) -> Result<Outcome> {
        let hash = hash(data);
        let mut adopted = false;
        match self.files.get(rel) {
            Some(prev) if *prev == hash => return Ok(Outcome::Unchanged),
            Some(_) => {}
            None => {
                let path = Path::new(rel);
                if path.exists() && !force {
                    if !is_legacy(path) {
                        return Ok(Outcome::SkippedPreExisting);
                    }
                    adopted = true;
                }
            }
        }
        write_bytes(Path::new(rel), data)?;
        self.files.insert(rel.to_string(), hash);
        Ok(if adopted {
            Outcome::Adopted
        } else {
            Outcome::Written
        })
    }

    pub fn mark_removed(&mut self, rel: &str) {
        self.files.remove(rel);
    }

    pub fn remove_prefix(&mut self, prefix: &str) {
        let prefix = prefix.to_string();
        let keys: Vec<String> = self
            .files
            .keys()
            .filter(|k| k.starts_with(&prefix))
            .cloned()
            .collect();
        for key in keys {
            self.files.remove(&key);
        }
    }
}

pub fn is_legacy(path: &Path) -> bool {
    fs::read_to_string(path)
        .map(|c| c.contains(LEGACY_MARKER))
        .unwrap_or(false)
}

fn hash(data: &[u8]) -> String {
    let mut h: u64 = 0xcbf29ce484222325;
    for b in data {
        h ^= *b as u64;
        h = h.wrapping_mul(0x100000001b3);
    }
    format!("{:016x}", h)
}

fn write_bytes(path: &Path, data: &[u8]) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("Failed to create {}", parent.display()))?;
    }
    fs::write(path, data).with_context(|| format!("Failed to write {}", path.display()))
}
